name = "Support-Develeper-Hugo-Theme"
description = "A Hugo theme for technical documentation sites"
homepage = "https://github.com/rackerlabs/support-developer-hugo-theme"
tags = ["documentation", "multilingual", "customizable", "responsive", "docs"]
features = []
min_version = 0.74

[author]
  name = "Rackerlabs"
  homepage = "https://github.com/rackerlabs/"
