name = "Support-Developer-Hugo-Theme"
description = "Theme for the Support Developer Blog Sites"
homepage = "https://github.com/rackerlabs/support-developer-hugo-theme"
tags = ["support-developer-hugo-theme"]
features = []
min_version = "0.0.1"

[author]
  name = "Rackelabs"
  homepage = "https://github.com/rackerlabs"

